name: Docker Hub

on:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . -t sashadavinci/devops-laba:${{ github.sha }}

      - name: Docker push
        run: docker push sashadavinci/devops-laba:${{ github.sha }}

      - name: Trigger Jenkins
        if: success()
        run: curl http://http://158.160.165.55:8080/job/Deploy/build?token=kldkDDh-k345j_73lkjhfdg43
